"use client";
import { useState } from "react";
import Image from "next/image";
import { useRouter } from "next/navigation";
import { Button } from "@/components/ui/button";

export default function ItemInfo() {
  const router = useRouter();

  const [itemName, setItemName] = useState("");
  const [price, setPrice] = useState("");
  const [description, setDescription] = useState("");

  return (
    <div>
      <div className="p-6 mx-auto bg-white rounded-md shadow-md">
        <h1 className="text-2xl font-bold mb-4">Item Information</h1>
        <p className="text-sm text-gray-500 mb-6">
          Generated by AI. Feel free to modify it.
        </p>
        <div className="mb-8">
          <Image
            src="/images/red_chair.png"
            alt="Red Chair"
            width={300}
            height={200}
            className="rounded-md"
          />
        </div>
        <form className="mt-6">
          <div className="mb-4">
            <label
              className="block text-sm font-medium mb-1"
              htmlFor="itemName"
            >
              Item Name
            </label>
            <input
              type="text"
              id="itemName"
              className="w-full px-3 py-2 border rounded-md"
              onChange={(e) => setItemName(e.target.value)}
              defaultValue="Red Chair"
            />
          </div>
          <div className="mb-4">
            <label className="block text-sm font-medium mb-1" htmlFor="price">
              Price (AI Suggested)
            </label>
            <input
              type="text"
              id="price"
              className="w-full px-3 py-2 border rounded-md"
              defaultValue="$10"
              onChange={(e) => setPrice(e.target.value)}
            />
          </div>
          <div className="mb-4">
            <label
              className="block text-sm font-medium mb-1"
              htmlFor="description"
            >
              Item Description
            </label>
            <textarea
              id="description"
              className="w-full px-3 py-2 border rounded-md"
              onChange={(e) => setDescription(e.target.value)}
              defaultValue="The wood chair is sturdy, simple, and painted in red, making it a practical and eye-catching piece of furniture."
            ></textarea>
          </div>
        </form>
        <div className="flex gap-2 mt-6">
          <Button
            onClick={() => router.back()}
            className="px-4 py-2 bg-gray-300 text-black rounded-md"
          >
            Back
          </Button>
          <Button
            onClick={() => {
              console.log({
                itemName,
                price,
                description,
              });
              router.push("/sell-items/item-info-filling/confirmation");
            }}
            className="bg-black text-white hover:bg-gray-700"
          >
            Continue
          </Button>
        </div>
      </div>
    </div>
  );
}
